CREATE TABLE "WRITER_BBS" (
	"WB_NO"	NUMBER		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL,
	"WB_TYPE"	VARCHAR2(1)		NOT NULL,
	"WB_TITLE"	VARCHAR2(60)		NOT NULL,
	"WB_CONTENT"	VARCHAR2(3900)		NOT NULL,
	"WB_COUNT"	NUMBER		NOT NULL,
	"WB_WRITER"	VARCHAR2(45)		NOT NULL,
	"WB_DATE"	TIMESTAMP		NOT NULL,
	"WB_ORIGINAL_FILENAME"	VARCHAR2(500)		NULL,
	"WB_RENAME_FILENAME"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "WRITER_BBS"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "WRITER_BBS"."WB_TYPE" IS '공지:N / 자유:F';

COMMENT ON COLUMN "WRITER_BBS"."WB_WRITER" IS 'EMP_NAME';

CREATE TABLE "WRITER_BBS_COMMENT" (
	"WBC_NO"	NUMBER		NOT NULL,
	"WB_NO"	NUMBER		NOT NULL,
	"WBC_CONTENT"	VARCHAR2(1024)		NOT NULL,
	"WBC_WRITER"	VARCHAR2(45)		NOT NULL,
	"WBC_DATE"	TIMESTAMP		NOT NULL
);

CREATE TABLE "COMPANY" (
	"CP_NO"	NUMBER		NOT NULL,
	"CP_NAME"	VARCHAR2(60)		NOT NULL,
	"CP_CATEGORY"	VARCHAR2(20)		NULL,
	"CP_BOSS"	VARCHAR2(30)	DEFAULT 'N'	NULL,
	"CP_ESTABLISH"	DATE		NULL,
	"CP_TEL"	NUMBER		NULL,
	"CP_POSTCODE"	VARCHAR2(20)		NULL,
	"CP_ADDRESS"	VARCHAR2(200)		NULL,
	"CP_DTADDRESS"	VARCHAR2(1000)		NULL,
	"CP_UPDATE"	TIMESTAMP		NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMPANY"."CP_CATEGORY" IS '법인/개인';

COMMENT ON COLUMN "COMPANY"."CP_ADDRESS" IS '주소API 사용';

COMMENT ON COLUMN "COMPANY"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "SCHEDULE_CALENDAR" (
	"SCD_NO"	NUMBER		NOT NULL,
	"SCD_WRITER"	VARCHAR2(100)		NOT NULL,
	"SCD_WRITE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"SCD_UPDATE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"SCD_TYPE"	VARCHAR2(1)		NOT NULL,
	"SCD_NAME"	VARCHAR2(100)		NOT NULL,
	"SCD_DATE"	VARCHAR2(40)		NOT NULL,
	"SCD_TIME"	VARCHAR2(40)		NOT NULL,
	"SCD_CONTENT"	VARCHAR2(4000)		NULL,
	"SCD_PLACE"	VARCHAR2(100)		NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SCHEDULE_CALENDAR"."SCD_NO" IS 'SEQ_SCD_NO';

COMMENT ON COLUMN "SCHEDULE_CALENDAR"."SCD_WRITE_DATE" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "SCHEDULE_CALENDAR"."SCD_UPDATE_DATE" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "SCHEDULE_CALENDAR"."SCD_TYPE" IS 'c : 기업,  p : 개인';

COMMENT ON COLUMN "SCHEDULE_CALENDAR"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "CHATMESSAGE" (
	"CH_MSGID"	VARCHAR(255)		NOT NULL,
	"CH_MSG"	VARCHAR(255)		NULL,
	"CH_TIME"	TIMESTAMP		NULL,
	"RM_ID"	VARCHAR(255)		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATMESSAGE"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "CHATROOM" (
	"RM_ID"	VARCHAR(255)		NOT NULL,
	"RM_NAME"	VARCHAR2(100)		NULL
);

CREATE TABLE "CHATROOMJOIN" (
	"JN_ID"	VARCHAR(255)		NOT NULL,
	"UM_NO"	VARCHAR(255)		NULL,
	"RM_ID"	VARCHAR(255)		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATROOMJOIN"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "ATTENDANCE" (
	"EMP_NO"	NUMBER		NOT NULL,
	"ATT_STATUS"	VARCHAR2(4)		NOT NULL,
	"ATT_START"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"ATT_END"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"ATT_TOTALTIME"	VARCHAR2(40)		NOT NULL,
	"ATT_OVERTIME"	VARCHAR2(40)		NOT NULL,
	"ATT_LIMITTIME"	VARCHAR2(40)		NOT NULL,
	"DO_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ATTENDANCE"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "ATTENDANCE"."ATT_STATUS" IS 'WK:업무중, OJ: 외근, LE: 조퇴, DO: 휴가(반차개념)';

COMMENT ON COLUMN "ATTENDANCE"."ATT_START" IS 'YYYY/MM/DD/HH:MI:SS';

COMMENT ON COLUMN "ATTENDANCE"."ATT_END" IS 'YYYY/MM/DD/HH:MI:SS';

COMMENT ON COLUMN "ATTENDANCE"."ATT_TOTALTIME" IS 'HH:MI';

COMMENT ON COLUMN "ATTENDANCE"."ATT_OVERTIME" IS 'HH:MI';

COMMENT ON COLUMN "ATTENDANCE"."ATT_LIMITTIME" IS 'HH:MI';

COMMENT ON COLUMN "ATTENDANCE"."DO_NO" IS 'SEQ_DO_NO';

CREATE TABLE "DEPT" (
	"DEPT_NO"	NUMBER		NOT NULL,
	"UPPER_DEPT_NO"	NUMBER		NOT NULL,
	"LOWER_DEPT_NO"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "DOCS_BOX" (
	"DOCS_NO"	NUMBER		NOT NULL,
	"DOCS_PATH"	VARCHAR2(500)		NULL,
	"DOCS_REALNAME"	VARCHAR2(500)		NULL,
	"DOCS_BUILDNAME"	VARCHAR2(500)		NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DOCS_BOX"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "ORG_POSITION" (
	"POSITION_NO"	NUMBER		NOT NULL,
	"POSITION_NAME"	VARCHAR2(100)		NOT NULL,
	"POSITION_LEVEL"	VARCHAR2(100)		NOT NULL,
	"UPPER_POSITION_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "ORG_POSITION"."POSITION_NO" IS 'SEQ_POSITION_NO';

CREATE TABLE "EMAIL" (
	"EM_SENDER"	VARCHAR2(100)		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL,
	"EM_NAME"	VARCHAR2(45)		NOT NULL,
	"EM_RECIPIENT"	VARCHAR2(100)		NOT NULL,
	"EM_TITLE"	VARCHAR2(100)		NULL,
	"EM_CONTENT"	VARCHAR2(3900)		NULL,
	"EM_FILENAME"	VARCHAR2(500)		NULL,
	"EM_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "EMAIL"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "GIVE_DOCS" (
	"DOCS_NO"	NUMBER		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "GIVE_DOCS"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "TAKE_DOCS" (
	"DOCS_NO"	NUMBER		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TAKE_DOCS"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "EMPLOYEE" (
	"EMP_NO"	NUMBER		NOT NULL,
	"DEPT_NO"	NUMBER		NOT NULL,
	"POSITION_NO"	NUMBER		NOT NULL,
	"EMP_PWD"	VARCHAR2(40)		NOT NULL,
	"EMP_ORIGINAL_FILENAME"	VARCHAR2(500)		NULL,
	"EMP_RENAME_FILENAME"	VARCHAR2(500)		NULL,
	"EMP_NAME"	VARCHAR2(20)		NOT NULL,
	"EMP_GENDER"	VARCHAR2(1)		NULL,
	"EMP_BIRTH"	VARCHAR2(20)		NOT NULL,
	"EMP_EMAIL"	VARCHAR2(100)		NOT NULL,
	"EMP_TEL"	VARCHAR2(20)		NOT NULL,
	"EMP_POSTCODE"	VARCHAR2(20)		NOT NULL,
	"EMP_ADDRESS"	VARCHAR2(100)		NOT NULL,
	"EMP_DETAIL_ADDRESS"	VARCHAR2(100)		NOT NULL,
	"EMP_WRITE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"EMP_UPDATE_DATE"	TIMESTAMP		NULL,
	"EMP_OUT_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "EMPLOYEE"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "EMPLOYEE"."EMP_GENDER" IS '남자 : M / 여자 : F/ 선택 안 함:D';

COMMENT ON COLUMN "EMPLOYEE"."EMP_BIRTH" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "EMPLOYEE"."EMP_EMAIL" IS 'AAA@EMAIL.COM';

COMMENT ON COLUMN "EMPLOYEE"."EMP_TEL" IS '010-0000-0000';

COMMENT ON COLUMN "EMPLOYEE"."EMP_ADDRESS" IS '주소 API';

COMMENT ON COLUMN "EMPLOYEE"."EMP_WRITE_DATE" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "EMPLOYEE"."EMP_UPDATE_DATE" IS 'YYYY/MM/DD';

CREATE TABLE "E_SIGN" (
	"SIGN_NO"	NUMBER		NOT NULL,
	"SIGN_PATH"	VARCHAR2(500)		NULL,
	"EMP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "E_SIGN"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "DELEGATE_AUTHORITY" (
	"AUTHORITY_GIVER"	NUMBER		NOT NULL,
	"AUTHORITY_TAKER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DELEGATE_AUTHORITY"."AUTHORITY_GIVER" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "DELEGATE_AUTHORITY"."AUTHORITY_TAKER" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

CREATE TABLE "E_APPROVAL" (
	"DRAFT_NO"	NUMBER		NOT NULL,
	"DRAFTER_ID"	NUMBER		NOT NULL,
	"DRAFT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"DRAFT_TITLE"	VARCHAR2(500)		NOT NULL,
	"DRAFT_CONTENT"	VARCHAR2(3900)		NOT NULL,
	"DRAFT_STATUS"	NUMBER		NOT NULL,
	"DRAFT_FIRST"	NUMBER		NOT NULL,
	"DRAFT_SECOND"	NUMBER		NULL,
	"DRAFT_THIRD"	NUMBER		NULL,
	"DRAFT_FOURTH"	NUMBER		NULL,
	"DRAFT_FIFTH"	NUMBER		NULL,
	"APPROVAL_STATUS"	NUMBER		NULL
);

COMMENT ON COLUMN "E_APPROVAL"."DRAFTER_ID" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "E_APPROVAL"."DRAFT_STATUS" IS '1.결재중, 2.결재완료,  3. 반려,  4.임시저장,  5.취소및회수';

COMMENT ON COLUMN "E_APPROVAL"."APPROVAL_STATUS" IS '1, 2, 3, 4, 5';

CREATE TABLE "E_FORMS" (
	"FORMS_NO"	NUMBER		NOT NULL,
	"FORMS_TITLE"	VARCHAR2(500)		NULL,
	"FORMS_CONTENT"	CLOB		NULL,
	"FORMS_HISTORY"	VARCHAR2(500)		NULL,
	"FORMS_DEPT"	NUMBER		NULL
);

CREATE TABLE "APP_FILE" (
	"FILE_NO"	NUMBER		NOT NULL,
	"DRAFT_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NULL,
	"FILE_REALNAME"	VARCHAR2(500)		NULL,
	"FILE_BUILDNAME"	VARCHAR2(500)		NULL
);

CREATE TABLE "BBS_FILE" (
	"BF_NO"	NUMBER		NOT NULL,
	"WB_NO"	NUMBER		NOT NULL,
	"BF_ORIGINAL_NAME"	VARCHAR2(50)		NULL,
	"BF_UPLOAD_NAME"	VARCHAR2(100)		NULL,
	"BF_PATH"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "BBS_FILE"."BF_NO" IS 'NVL(MAX(NO), 0 )+1';

CREATE TABLE "EMAIL_FILE" (
	"EF_NO"	NUMBER		NOT NULL,
	"EM_SENDER"	VARCHAR2(100)		NOT NULL,
	"EF_ORIGINAL_NAME"	VARCHAR2(50)		NULL,
	"EF_UPLOAD_NAME"	VARCHAR2(100)		NULL,
	"EF_PATH"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "EMAIL_FILE"."EF_NO" IS 'NVL(MAX(NO), 0 )+1';

CREATE TABLE "DAY_OFF" (
	"DO_NO"	NUMBER		NOT NULL,
	"EMP_NO"	NUMBER		NOT NULL,
	"DO_DATE"	VARCHAR2(40)		NOT NULL,
	"DO_TYPE"	VARCHAR2(1)		NOT NULL,
	"DO_COUNT"	NUMBER		NOT NULL,
	"DO_TOTAL"	NUMBER		NOT NULL,
	"DO_USE_DATE"	VARCHAR2(40)		NULL,
	"DO_USE_TYPE"	VARCHAR2(1)		NULL,
	"DO_USE_COUNT"	NUMBER		NULL,
	"DO_REST"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DAY_OFF"."DO_NO" IS 'SEQ_DO_NO';

COMMENT ON COLUMN "DAY_OFF"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "DAY_OFF"."DO_DATE" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "DAY_OFF"."DO_TYPE" IS 'A: 가산, B:기본';

COMMENT ON COLUMN "DAY_OFF"."DO_USE_DATE" IS 'YYYY/MM/DD';

COMMENT ON COLUMN "DAY_OFF"."DO_USE_TYPE" IS 'A:법정휴가, H:반차, E: 경조사,  S: 병가';

CREATE TABLE "CLAUSE" (
	"CU_CODE"	NUMBER		NOT NULL,
	"CU_NAME"	VARCHAR2(20)		NOT NULL,
	"CU_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CU_REQURIRED"	VARCHAR2(1)		NOT NULL
);

COMMENT ON COLUMN "CLAUSE"."CU_CODE" IS '이용약관 01/개인정보수집 및 이용 동의 02/위치정보서비스 동의03';

COMMENT ON COLUMN "CLAUSE"."CU_REQURIRED" IS '필수 : Y / 필수 아님 : N';

CREATE TABLE "C_AGREEMENT" (
	"EMP_NO"	NUMBER		NOT NULL,
	"CU_CODE"	NUMBER		NOT NULL,
	"CU_AGR"	VARCHAR2(1)		NOT NULL,
	"CU_DATE"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "C_AGREEMENT"."EMP_NO" IS '년도4자리+부서번호2자리+가입순서 3자리(000~)';

COMMENT ON COLUMN "C_AGREEMENT"."CU_CODE" IS '이용약관 01/개인정보수집 및 이용 동의 02/위치정보서비스 동의03';

COMMENT ON COLUMN "C_AGREEMENT"."CU_AGR" IS '동의 : Y / 미동의 : N';

ALTER TABLE "WRITER_BBS" ADD CONSTRAINT "PK_WRITER_BBS" PRIMARY KEY (
	"WB_NO"
);

ALTER TABLE "WRITER_BBS_COMMENT" ADD CONSTRAINT "PK_WRITER_BBS_COMMENT" PRIMARY KEY (
	"WBC_NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"CP_NO"
);

ALTER TABLE "SCHEDULE_CALENDAR" ADD CONSTRAINT "PK_SCHEDULE_CALENDAR" PRIMARY KEY (
	"SCD_NO"
);

ALTER TABLE "CHATMESSAGE" ADD CONSTRAINT "PK_CHATMESSAGE" PRIMARY KEY (
	"CH_MSGID"
);

ALTER TABLE "CHATROOM" ADD CONSTRAINT "PK_CHATROOM" PRIMARY KEY (
	"RM_ID"
);

ALTER TABLE "CHATROOMJOIN" ADD CONSTRAINT "PK_CHATROOMJOIN" PRIMARY KEY (
	"JN_ID"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY (
	"DEPT_NO"
);

ALTER TABLE "DOCS_BOX" ADD CONSTRAINT "PK_DOCS_BOX" PRIMARY KEY (
	"DOCS_NO"
);

ALTER TABLE "ORG_POSITION" ADD CONSTRAINT "PK_ORG_POSITION" PRIMARY KEY (
	"POSITION_NO"
);

ALTER TABLE "EMAIL" ADD CONSTRAINT "PK_EMAIL" PRIMARY KEY (
	"EM_SENDER"
);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY (
	"EMP_NO"
);

ALTER TABLE "E_SIGN" ADD CONSTRAINT "PK_E_SIGN" PRIMARY KEY (
	"SIGN_NO"
);

ALTER TABLE "E_APPROVAL" ADD CONSTRAINT "PK_E_APPROVAL" PRIMARY KEY (
	"DRAFT_NO"
);

ALTER TABLE "E_FORMS" ADD CONSTRAINT "PK_E_FORMS" PRIMARY KEY (
	"FORMS_NO"
);

ALTER TABLE "APP_FILE" ADD CONSTRAINT "PK_APP_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "BBS_FILE" ADD CONSTRAINT "PK_BBS_FILE" PRIMARY KEY (
	"BF_NO"
);

ALTER TABLE "EMAIL_FILE" ADD CONSTRAINT "PK_EMAIL_FILE" PRIMARY KEY (
	"EF_NO"
);

ALTER TABLE "DAY_OFF" ADD CONSTRAINT "PK_DAY_OFF" PRIMARY KEY (
	"DO_NO"
);

ALTER TABLE "CLAUSE" ADD CONSTRAINT "PK_CLAUSE" PRIMARY KEY (
	"CU_CODE"
);

ALTER TABLE "WRITER_BBS" ADD CONSTRAINT "FK_EMPLOYEE_TO_WRITER_BBS_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "WRITER_BBS_COMMENT" ADD CONSTRAINT "FK_WRITERBBS_WRITERBBSCOMMENT" FOREIGN KEY (
	"WB_NO"
)
REFERENCES "WRITER_BBS" (
	"WB_NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "FK_EMPLOYEE_TO_COMPANY_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "SCHEDULE_CALENDAR" ADD CONSTRAINT "FK_EMPLOYEE_SCHEDULECALENDAR" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "CHATMESSAGE" ADD CONSTRAINT "FK_CHATROOM_TO_CHATMESSAGE_1" FOREIGN KEY (
	"RM_ID"
)
REFERENCES "CHATROOM" (
	"RM_ID"
);

ALTER TABLE "CHATMESSAGE" ADD CONSTRAINT "FK_EMPLOYEE_TO_CHATMESSAGE_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "CHATROOMJOIN" ADD CONSTRAINT "FK_CHATROOM_TO_CHATROOMJOIN_1" FOREIGN KEY (
	"RM_ID"
)
REFERENCES "CHATROOM" (
	"RM_ID"
);

ALTER TABLE "CHATROOMJOIN" ADD CONSTRAINT "FK_EMPLOYEE_TO_CHATROOMJOIN_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "FK_EMPLOYEE_TO_ATTENDANCE_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "FK_DAY_OFF_TO_ATTENDANCE_1" FOREIGN KEY (
	"DO_NO"
)
REFERENCES "DAY_OFF" (
	"DO_NO"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "FK_DEPT_TO_DEPT_1" FOREIGN KEY (
	"UPPER_DEPT_NO"
)
REFERENCES "DEPT" (
	"DEPT_NO"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "FK_DEPT_TO_DEPT_2" FOREIGN KEY (
	"LOWER_DEPT_NO"
)
REFERENCES "DEPT" (
	"DEPT_NO"
);

ALTER TABLE "DOCS_BOX" ADD CONSTRAINT "FK_EMPLOYEE_TO_DOCS_BOX_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "ORG_POSITION" ADD CONSTRAINT "FK_ORGPOSITION_ORG_POSITION" FOREIGN KEY (
	"UPPER_POSITION_NO"
)
REFERENCES "ORG_POSITION" (
	"POSITION_NO"
);

ALTER TABLE "EMAIL" ADD CONSTRAINT "FK_EMPLOYEE_TO_EMAIL_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "GIVE_DOCS" ADD CONSTRAINT "FK_DOCS_BOX_TO_GIVE_DOCS_1" FOREIGN KEY (
	"DOCS_NO"
)
REFERENCES "DOCS_BOX" (
	"DOCS_NO"
);

ALTER TABLE "GIVE_DOCS" ADD CONSTRAINT "FK_EMPLOYEE_TO_GIVE_DOCS_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "TAKE_DOCS" ADD CONSTRAINT "FK_DOCS_BOX_TO_TAKE_DOCS_1" FOREIGN KEY (
	"DOCS_NO"
)
REFERENCES "DOCS_BOX" (
	"DOCS_NO"
);

ALTER TABLE "TAKE_DOCS" ADD CONSTRAINT "FK_EMPLOYEE_TO_TAKE_DOCS_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_DEPT_TO_EMPLOYEE_1" FOREIGN KEY (
	"DEPT_NO"
)
REFERENCES "DEPT" (
	"DEPT_NO"
);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_ORG_POSITION_TO_EMPLOYEE_1" FOREIGN KEY (
	"POSITION_NO"
)
REFERENCES "ORG_POSITION" (
	"POSITION_NO"
);

ALTER TABLE "E_SIGN" ADD CONSTRAINT "FK_EMPLOYEE_TO_E_SIGN_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "DELEGATE_AUTHORITY" ADD CONSTRAINT "FK_EMPLOYEE_DELEGATEAUTH" FOREIGN KEY (
	"AUTHORITY_GIVER"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "DELEGATE_AUTHORITY" ADD CONSTRAINT "FK_EMPLOYEE_DELEGATEAUTH2" FOREIGN KEY (
	"AUTHORITY_TAKER"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "E_APPROVAL" ADD CONSTRAINT "FK_EMPLOYEE_TO_E_APPROVAL_1" FOREIGN KEY (
	"DRAFTER_ID"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "E_FORMS" ADD CONSTRAINT "FK_DEPT_TO_E_FORMS_1" FOREIGN KEY (
	"FORMS_DEPT"
)
REFERENCES "DEPT" (
	"DEPT_NO"
);

ALTER TABLE "APP_FILE" ADD CONSTRAINT "FK_E_APPROVAL_TO_APP_FILE_1" FOREIGN KEY (
	"DRAFT_NO"
)
REFERENCES "E_APPROVAL" (
	"DRAFT_NO"
);

ALTER TABLE "BBS_FILE" ADD CONSTRAINT "FK_WRITER_BBS_TO_BBS_FILE_1" FOREIGN KEY (
	"WB_NO"
)
REFERENCES "WRITER_BBS" (
	"WB_NO"
);

ALTER TABLE "EMAIL_FILE" ADD CONSTRAINT "FK_EMAIL_TO_EMAIL_FILE_1" FOREIGN KEY (
	"EM_SENDER"
)
REFERENCES "EMAIL" (
	"EM_SENDER"
);

ALTER TABLE "DAY_OFF" ADD CONSTRAINT "FK_EMPLOYEE_TO_DAY_OFF_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "C_AGREEMENT" ADD CONSTRAINT "FK_EMPLOYEE_TO_C_AGREEMENT_1" FOREIGN KEY (
	"EMP_NO"
)
REFERENCES "EMPLOYEE" (
	"EMP_NO"
);

ALTER TABLE "C_AGREEMENT" ADD CONSTRAINT "FK_CLAUSE_TO_C_AGREEMENT_1" FOREIGN KEY (
	"CU_CODE"
)
REFERENCES "CLAUSE" (
	"CU_CODE"
);